- name: Copy keyboard files
        run: |
          mkdir -p ~/qmk_firmware/keyboards/kiiboom/cybrix16/keymaps/via
          cp $GITHUB_WORKSPACE/keyboards/kiiboom/cybrix16/info.json ~/qmk_firmware/keyboards/kiiboom/cybrix16/
          cp $GITHUB_WORKSPACE/keyboards/kiiboom/cybrix16/config.h ~/qmk_firmware/keyboards/kiiboom/cybrix16/
          cp $GITHUB_WORKSPACE/keyboards/kiiboom/cybrix16/rules.mk ~/qmk_firmware/keyboards/kiiboom/cybrix16/
          cp $GITHUB_WORKSPACE/keyboards/kiiboom/cybrix16/keymaps/via/keymap.c ~/qmk_firmware/keyboards/kiiboom/cybrix16/keymaps/via/
          cp $GITHUB_WORKSPACE/keyboards/kiiboom/cybrix16/keymaps/via/rules.mk ~/qmk_firmware/keyboards/kiiboom/cybrix16/keymaps/via/

      - name: Debug - list files
        run: |
          echo "=== Fork workspace ==="
          ls $GITHUB_WORKSPACE/keyboards/kiiboom/cybrix16/
          echo "=== QMK target ==="
          ls ~/qmk_firmware/keyboards/kiiboom/cybrix16/
